name: knowledge-graph-llms
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - jupyter>=1.0.0
  - scikit-learn>=1.1.0
  - scipy>=1.9.0
  - pip
  - pip:
    - networkx>=2.8
    - plotly>=5.0.0
    - openai>=1.0.0
    - langchain>=0.1.0
    - langchain-experimental>=0.0.50
    - langchain-openai>=0.0.8
    - python-dotenv>=0.19.0
